#!/usr/bin/env python
"""
debgit-get-version <branch> [options]

Generate a software version based on the given branch and the current time.



root@lucid64:/appscale/appscale# git describe --tags
0.0.1-5-gff4eb19
root@lucid64:/appscale/appscale# git tag -d 0.0.1
Deleted tag '0.0.1' (was 92839d3)
root@lucid64:/appscale/appscale# git describe --tags
fatal: No names found, cannot describe anything.
"""
import os
import sys

import time

from clint.command import Command


class Debchange(Command):
    def run(self):
        now = time.strftime('%y%j.%H%M')

        print now


if __name__ == '__main__':
    command = Debchange()
    try:
        command.run()
    except KeyboardInterrupt:
        command.quit()
