#!/usr/bin/env python
import os
import sys
import time

from clint.command import Command

from debgit.changelog import get_changelog_entries


class GetChangelogEntries(Command):
    """
    debgit-get-changelog

    Generate a changelog list between the current revision and the last tag.
    """

    def __init__(self, doc=None):
        super(GetChangelogEntries, self).__init__(doc=doc or __doc__)

    def run(self):
        for entry in get_changelog_entries():
            print(entry)


if __name__ == '__main__':
    command = GetChangelogEntries()
    try:
        sys.exit(command.run() or 0)
    except KeyboardInterrupt:
        command.quit()
